#pragma once

#include <stdint.h>

enum class ActionType : uint8_t {
    Fist = 0,
    Wrench,
    Door,
    Lock,
    Gems,
    MysteryBlock,
    InstantDeath, //spike etc
    BouncyOnTop,  //mushrooms
    Consumable,
    OpenOnStep, //house entrance etc
    Sign,
    ChangesWhenHit,
    TogglesWhenHit,
    WorldDoor,
    Platform,
    UnbreakableBedrock,
    PainOnTouchlava, //Lava etc
    ForegroundLayerTile,
    BackgroundLayerTile,
    Seed,
    Equipment = 20,
    Clothes = 20,
    AnimatedForegroundTile,
    SoundOnStep,
    ArtWall,
    BouncyOnAllSides, //bumper (the shit that is originally in antibounce)
    PainOnTouchCactus,
    InstantTeleportation, //portal
    Checkpoint,
    SheetMusic,
    Slippery, //Ice
    UNUSED,
    KillOnClose, //Dragon gate
    ItemStorage, //treasure chest, giant clam, etc
    MailBox,
    MessageStorage, //bulletin board, guestbook, etc.
    ItemSurprise,
    DiceBlock,
    ChemicalIngredient,
    Provider,
    ChemicalCombiner,
    AchiementBlock,
    WeatherMachine,
    Scoreboard,
    Sungate,
    Profile,
    KillOnEnterButNotSolid, //Evil eye etc
    HeartMonitor,
    DonateBox,
    UNUSED2,
    Mannequin,
    SecurityCamera, //CCTV
    BunnyEgg,
    GameBlock, //ex. flag, game pack shit
    GameGenerator,
    XenoniteCrystal,
    PhoneBooth,
    Crystal,
    Crime,
    Compactor, //Food grinder, clothing compactor, uses many amounts of items to produce smaller amounts of rare items
    Spotlight,
    Wind, //also shit like turbo fans, just hsit that makes moving to 1 dir harder and to 1 easier
    DisplayBlock,
    VendingMachine,
    FishTankPort,
    Fish,
    SolarCollector,
    Forge,
    GivingTree,
    GivingTreeStump,
    Steam,
    SteamVent,
    SteamOrgan,
    SilkWorm,
    SewingMachine,
    CountryFlag,
    LobsterTrap,
    PaintingEasel,
    BattlePetCage,
    PetTrainer,
    SteamEngine,
    LockBot,
    Weather2, //usually these are somehow special like background machine has extra param
    SpiritStorage,
    DisplayShelf,
    VIPEntrance,
    ChallengeTimer,
    ChallengeFlag,
    WallMount,
    Portrait,
    WeatherSpecial, //Weathers where u can choose the weather (ex. guild, stuff, etc)
    Fossil,
    FossilPrepStation,
    DNAProcessor,
    Howler, //Shoots deadly particles at people, like a tower in at ower defense game
    ValhowlaTreasure,
    ChemsynthProcessor,
    ChemsynthTank,
    StorageBox, //Store items here
    Oven,
    AudioBlock,
    GeigerCharger,
    AdventureBegins,
    TombRobber,
    BallonOMatic,
    TeamEntrance1,
    TeamEntrance2,
    TeamEntrance3,
    Artifact,
    LemonJelly,
    TrainingPort,
    FishableWithSpecialEquipment, //if u use water bucket and an extractor for t he specific blok u cna extract items by fishing (lol)
    CollectorBlock,               //Magplant, unstable tesseract, etc
    MagplantRemote,
    CyBot,
    CyBotCommand,
    LuckyToken,
    GrowScan,
    ContainmentFieldNode,
    SpiritBoard,
    WorldArchitech,
    StarshipItem,
    UNUSED3,
    PullsPlayersTowards,
    TesseractManipulator,
    HeartOfGaia,
    TechnoOrganicEngine,
    StormCloud,
    DisappearWhenSteppedOn,
    Mud,
    BountifulSeed,
    SafeVault,
    PlaceholderFix = 222, //not real, used for guild flag and data starship hull fixes
};

enum class TileExtraType : uint8_t {
    None = 0,
    Door = 1,
    Sign = 2,
    Lock = 3,
    Seed = 4,
    MailBox = 6,
    Unknown0 = 7,
    DiceBlock = 8,
    Provider = 9,
    AchievementBlock = 10,
    HeartMonitor = 11,
    DonateBox = 12,
    UNUSED2 = 13,
    Mannequin = 14,
    BunnyEgg = 15,
    GameBlock = 16,
    GameGenerator = 17,
    Xenonite = 18,
    PhoneBooth = 19,
    Crystal = 20,
    Crime = 21,
    Spotlight = 22,
    DisplayBlock = 23,
    VendingMachine = 24,
    FishTankPort = 25,
    SolarCollector = 26,
    Forge = 27,
    GivingTree = 28,
    GivingTreeStump = 29,
    SteamOrgan = 30,
    SilkWorm = 31,
    SewingMachine = 32,
    CountryOrChallengeFlag = 33,
    LobsterTrap = 34,
    PaintingEasel = 35,
    BattlePetCage = 36,
    PetTrainer = 37,
    SteamEngine = 38,
    LockBot = 39,
    Weather2 = 40,
    SpiritStorage = 41,
    UnbreakableBedrock = 42,
    DisplayShelf = 43,
    VIPEntrance = 44,
    ChallengeTimer = 45,
    ChallengeFlagUnused = 46,
    WallMount = 47,
    Portrait = 48,
    WeatherSpecial = 49,
    FossilPrepStation = 50,
    DNAProcessor = 51,
    Howler = 52,
    ChemsynthTank = 53,
    StorageBox = 54,
    Oven = 55,
    AudioBlock = 56,
    GeigerCharger = 57,
    AdventureBegins = 58,
    TombRobber = 59,
    BalloonOMaticOrTeamEntrance = 60,
    TrainingPort = 61,
    CollectorBlock = 62,
    CyBot = 63,
    LuckyToken = 64,
    Guild = 65,
    GrowScan = 66,
    ContainmentFieldNode = 67,
    SpiritBoard = 68,
    TesseractManipulator = 69,
    HeartOfGaia = 70,
    TechnoOrganicEngine = 71,
    StormCloud = 72,
    DisappearWhenSteppedOn = 73,
    SafeVault = 74,
    InfinityWeather = 77,
    PlaceholderFix = 222,   //not real, used for guild item shit
    DataStarshipHull = 223, //data starship hull
};

enum TileCollision : uint8_t {
    None,
    Solid,
    JumpThrough,
    Gateway,
    IfOff,
    OneWayHorizontal,
    VIP,
    JumpDown,
    Adventure,
    IfOn,
    Faction,
    Guild,
    Cloud,
};

enum class TileFlags : uint16_t {
    TileExtra = 1 << 0,
    Locked = 1 << 1,
    FacingLeft = 1 << 5,
    Toggled = 1 << 6,
    Public = 1 << 7,
    Silent = 1 << 9,
    Water = 1 << 10,
    Glue = 1 << 11,
    Fire = 1 << 12,
    Red = 1 << 13,
    Green = 1 << 14,
    Blue = 1 << 15
};